name: Tests

on: 
  pull_request:
    branches: [ main, develop ]
    types: [ opened, synchronize ]
  push:
    branches: [ main, develop ]

jobs:
  unity-test:
    name: Checkout and Run Unity Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      - uses: actions/cache@v2
        with:
          path: ulox-example/Library
          key: ulox-example/Library

      - name: Run Unity tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          projectPath: ulox-example/
